// Mocks generated by Mockito from annotations
// in flutter_account_manager/test/account_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

import 'package:flutter_account_manager/src/generated/account_manager_api.g.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthTokenResult_0 extends _i1.SmartFake
    implements _i2.AuthTokenResult {
  _FakeAuthTokenResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AccountManagerHostApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountManagerHostApi extends _i1.Mock
    implements _i2.AccountManagerHostApi {
  MockAccountManagerHostApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get pigeonVar_messageChannelSuffix => (super.noSuchMethod(
        Invocation.getter(#pigeonVar_messageChannelSuffix),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#pigeonVar_messageChannelSuffix),
        ),
      ) as String);

  @override
  _i4.Future<bool> addAccount(
    _i2.AccountData? account,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addAccount,
          [
            account,
            password,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<List<_i2.AccountData>> getAccounts(String? accountType) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAccounts,
          [accountType],
        ),
        returnValue:
            _i4.Future<List<_i2.AccountData>>.value(<_i2.AccountData>[]),
      ) as _i4.Future<List<_i2.AccountData>>);

  @override
  _i4.Future<_i2.AccountData?> getAccount(
    String? username,
    String? accountType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAccount,
          [
            username,
            accountType,
          ],
        ),
        returnValue: _i4.Future<_i2.AccountData?>.value(),
      ) as _i4.Future<_i2.AccountData?>);

  @override
  _i4.Future<bool> updateAccount(_i2.AccountData? account) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAccount,
          [account],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> removeAccount(_i2.AccountData? account) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeAccount,
          [account],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> accountExists(
    String? username,
    String? accountType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #accountExists,
          [
            username,
            accountType,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> updateCredentials(
    _i2.AccountData? account,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCredentials,
          [
            account,
            newPassword,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> validateCredentials(
    String? username,
    String? password,
    String? accountType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateCredentials,
          [
            username,
            password,
            accountType,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> clearCredentials(_i2.AccountData? account) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearCredentials,
          [account],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<_i2.AuthTokenResult> getAuthToken(
    _i2.AccountData? account,
    String? tokenType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAuthToken,
          [
            account,
            tokenType,
          ],
        ),
        returnValue:
            _i4.Future<_i2.AuthTokenResult>.value(_FakeAuthTokenResult_0(
          this,
          Invocation.method(
            #getAuthToken,
            [
              account,
              tokenType,
            ],
          ),
        )),
      ) as _i4.Future<_i2.AuthTokenResult>);

  @override
  _i4.Future<bool> setAuthToken(
    _i2.AccountData? account,
    String? tokenType,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAuthToken,
          [
            account,
            tokenType,
            token,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> invalidateAuthToken(
    String? accountType,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #invalidateAuthToken,
          [
            accountType,
            token,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> invalidateAllTokens(
    _i2.AccountData? account,
    String? tokenType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #invalidateAllTokens,
          [
            account,
            tokenType,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<List<String>> getAvailableTokenTypes(_i2.AccountData? account) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailableTokenTypes,
          [account],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<bool> openAccountSettings() => (super.noSuchMethod(
        Invocation.method(
          #openAccountSettings,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> isConfigured() => (super.noSuchMethod(
        Invocation.method(
          #isConfigured,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<Map<String, bool>> getPlatformCapabilities() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlatformCapabilities,
          [],
        ),
        returnValue: _i4.Future<Map<String, bool>>.value(<String, bool>{}),
      ) as _i4.Future<Map<String, bool>>);
}
