// Autogenerated from Pigeon (v29.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.lkrjangid.account_manager

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object AccountManagerApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * Represents a user account with associated metadata
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AccountData (
  val username: String,
  val accountType: String,
  val displayName: String? = null,
  val userData: Map<String?, String?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AccountData {
      val username = pigeonVar_list[0] as String
      val accountType = pigeonVar_list[1] as String
      val displayName = pigeonVar_list[2] as String?
      val userData = pigeonVar_list[3] as Map<String?, String?>?
      return AccountData(username, accountType, displayName, userData)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      username,
      accountType,
      displayName,
      userData,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AccountData
    return AccountManagerApiPigeonUtils.deepEquals(this.username, other.username) && AccountManagerApiPigeonUtils.deepEquals(this.accountType, other.accountType) && AccountManagerApiPigeonUtils.deepEquals(this.displayName, other.displayName) && AccountManagerApiPigeonUtils.deepEquals(this.userData, other.userData)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AccountManagerApiPigeonUtils.deepHash(this.username)
    result = 31 * result + AccountManagerApiPigeonUtils.deepHash(this.accountType)
    result = 31 * result + AccountManagerApiPigeonUtils.deepHash(this.displayName)
    result = 31 * result + AccountManagerApiPigeonUtils.deepHash(this.userData)
    return result
  }
  override fun toString(): String {
    return "AccountData(username=$username, accountType=$accountType, displayName=$displayName, userData=$userData)"
  }
}

/**
 * Auth token request result
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AuthTokenResult (
  val token: String? = null,
  val errorCode: Long? = null,
  val errorMessage: String? = null,
  val requiresUserInteraction: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AuthTokenResult {
      val token = pigeonVar_list[0] as String?
      val errorCode = pigeonVar_list[1] as Long?
      val errorMessage = pigeonVar_list[2] as String?
      val requiresUserInteraction = pigeonVar_list[3] as Boolean?
      return AuthTokenResult(token, errorCode, errorMessage, requiresUserInteraction)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      token,
      errorCode,
      errorMessage,
      requiresUserInteraction,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AuthTokenResult
    return AccountManagerApiPigeonUtils.deepEquals(this.token, other.token) && AccountManagerApiPigeonUtils.deepEquals(this.errorCode, other.errorCode) && AccountManagerApiPigeonUtils.deepEquals(this.errorMessage, other.errorMessage) && AccountManagerApiPigeonUtils.deepEquals(this.requiresUserInteraction, other.requiresUserInteraction)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AccountManagerApiPigeonUtils.deepHash(this.token)
    result = 31 * result + AccountManagerApiPigeonUtils.deepHash(this.errorCode)
    result = 31 * result + AccountManagerApiPigeonUtils.deepHash(this.errorMessage)
    result = 31 * result + AccountManagerApiPigeonUtils.deepHash(this.requiresUserInteraction)
    return result
  }
  override fun toString(): String {
    return "AuthTokenResult(token=$token, errorCode=$errorCode, errorMessage=$errorMessage, requiresUserInteraction=$requiresUserInteraction)"
  }
}
private open class AccountManagerApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AccountData.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AuthTokenResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is AccountData -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is AuthTokenResult -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface AccountManagerHostApi {
  fun addAccount(account: AccountData, password: String, callback: (Result<Boolean>) -> Unit)
  fun getAccounts(accountType: String, callback: (Result<List<AccountData>>) -> Unit)
  fun getAccount(username: String, accountType: String, callback: (Result<AccountData?>) -> Unit)
  fun updateAccount(account: AccountData, callback: (Result<Boolean>) -> Unit)
  fun removeAccount(account: AccountData, callback: (Result<Boolean>) -> Unit)
  fun accountExists(username: String, accountType: String, callback: (Result<Boolean>) -> Unit)
  fun updateCredentials(account: AccountData, newPassword: String, callback: (Result<Boolean>) -> Unit)
  fun validateCredentials(username: String, password: String, accountType: String, callback: (Result<Boolean>) -> Unit)
  fun clearCredentials(account: AccountData, callback: (Result<Boolean>) -> Unit)
  fun getAuthToken(account: AccountData, tokenType: String, callback: (Result<AuthTokenResult>) -> Unit)
  fun setAuthToken(account: AccountData, tokenType: String, token: String, callback: (Result<Boolean>) -> Unit)
  fun invalidateAuthToken(accountType: String, token: String, callback: (Result<Boolean>) -> Unit)
  fun invalidateAllTokens(account: AccountData, tokenType: String, callback: (Result<Boolean>) -> Unit)
  fun getAvailableTokenTypes(account: AccountData, callback: (Result<List<String>>) -> Unit)
  fun openAccountSettings(callback: (Result<Boolean>) -> Unit)
  fun isConfigured(callback: (Result<Boolean>) -> Unit)
  fun getPlatformCapabilities(callback: (Result<Map<String, Boolean>>) -> Unit)

  companion object {
    /** The codec used by AccountManagerHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      AccountManagerApiPigeonCodec()
    }
    /** Sets up an instance of `AccountManagerHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: AccountManagerHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_account_manager.AccountManagerHostApi.addAccount$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accountArg = args[0] as AccountData
            val passwordArg = args[1] as String
            api.addAccount(accountArg, passwordArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AccountManagerApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AccountManagerApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_account_manager.AccountManagerHostApi.getAccounts$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accountTypeArg = args[0] as String
            api.getAccounts(accountTypeArg) { result: Result<List<AccountData>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AccountManagerApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AccountManagerApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_account_manager.AccountManagerHostApi.getAccount$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val usernameArg = args[0] as String
            val accountTypeArg = args[1] as String
            api.getAccount(usernameArg, accountTypeArg) { result: Result<AccountData?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AccountManagerApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AccountManagerApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_account_manager.AccountManagerHostApi.updateAccount$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accountArg = args[0] as AccountData
            api.updateAccount(accountArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AccountManagerApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AccountManagerApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_account_manager.AccountManagerHostApi.removeAccount$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accountArg = args[0] as AccountData
            api.removeAccount(accountArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AccountManagerApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AccountManagerApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_account_manager.AccountManagerHostApi.accountExists$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val usernameArg = args[0] as String
            val accountTypeArg = args[1] as String
            api.accountExists(usernameArg, accountTypeArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AccountManagerApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AccountManagerApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_account_manager.AccountManagerHostApi.updateCredentials$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accountArg = args[0] as AccountData
            val newPasswordArg = args[1] as String
            api.updateCredentials(accountArg, newPasswordArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AccountManagerApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AccountManagerApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_account_manager.AccountManagerHostApi.validateCredentials$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val usernameArg = args[0] as String
            val passwordArg = args[1] as String
            val accountTypeArg = args[2] as String
            api.validateCredentials(usernameArg, passwordArg, accountTypeArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AccountManagerApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AccountManagerApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_account_manager.AccountManagerHostApi.clearCredentials$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accountArg = args[0] as AccountData
            api.clearCredentials(accountArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AccountManagerApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AccountManagerApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_account_manager.AccountManagerHostApi.getAuthToken$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accountArg = args[0] as AccountData
            val tokenTypeArg = args[1] as String
            api.getAuthToken(accountArg, tokenTypeArg) { result: Result<AuthTokenResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AccountManagerApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AccountManagerApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_account_manager.AccountManagerHostApi.setAuthToken$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accountArg = args[0] as AccountData
            val tokenTypeArg = args[1] as String
            val tokenArg = args[2] as String
            api.setAuthToken(accountArg, tokenTypeArg, tokenArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AccountManagerApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AccountManagerApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_account_manager.AccountManagerHostApi.invalidateAuthToken$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accountTypeArg = args[0] as String
            val tokenArg = args[1] as String
            api.invalidateAuthToken(accountTypeArg, tokenArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AccountManagerApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AccountManagerApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_account_manager.AccountManagerHostApi.invalidateAllTokens$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accountArg = args[0] as AccountData
            val tokenTypeArg = args[1] as String
            api.invalidateAllTokens(accountArg, tokenTypeArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AccountManagerApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AccountManagerApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_account_manager.AccountManagerHostApi.getAvailableTokenTypes$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accountArg = args[0] as AccountData
            api.getAvailableTokenTypes(accountArg) { result: Result<List<String>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AccountManagerApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AccountManagerApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_account_manager.AccountManagerHostApi.openAccountSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.openAccountSettings{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AccountManagerApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AccountManagerApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_account_manager.AccountManagerHostApi.isConfigured$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.isConfigured{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AccountManagerApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AccountManagerApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_account_manager.AccountManagerHostApi.getPlatformCapabilities$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getPlatformCapabilities{ result: Result<Map<String, Boolean>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AccountManagerApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AccountManagerApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class AccountCallbackFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by AccountCallbackFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      AccountManagerApiPigeonCodec()
    }
  }
  suspend fun onAccountAdded(accountArg: AccountData)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.flutter_account_manager.AccountCallbackFlutterApi.onAccountAdded$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(accountArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(AccountManagerApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun onAccountRemoved(accountArg: AccountData)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.flutter_account_manager.AccountCallbackFlutterApi.onAccountRemoved$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(accountArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(AccountManagerApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun onAccountUpdated(accountArg: AccountData)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.flutter_account_manager.AccountCallbackFlutterApi.onAccountUpdated$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(accountArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(AccountManagerApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun onAuthTokenExpired(accountArg: AccountData, tokenTypeArg: String)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.flutter_account_manager.AccountCallbackFlutterApi.onAuthTokenExpired$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(accountArg, tokenTypeArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(AccountManagerApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
}
