// Autogenerated from Pigeon (v29.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>"))"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum AccountManagerApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Represents a user account with associated metadata
///
/// Generated class from Pigeon that represents data sent in messages.
struct AccountData: Hashable, CustomStringConvertible {
  var username: String
  var accountType: String
  var displayName: String? = nil
  var userData: [String?: String?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AccountData? {
    let username = pigeonVar_list[0] as! String
    let accountType = pigeonVar_list[1] as! String
    let displayName: String? = nilOrValue(pigeonVar_list[2])
    let userData: [String?: String?]? = nilOrValue(pigeonVar_list[3])

    return AccountData(
      username: username,
      accountType: accountType,
      displayName: displayName,
      userData: userData
    )
  }
  func toList() -> [Any?] {
    return [
      username,
      accountType,
      displayName,
      userData,
    ]
  }
  static func == (lhs: AccountData, rhs: AccountData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return AccountManagerApiPigeonInternal.deepEquals(lhs.username, rhs.username) && AccountManagerApiPigeonInternal.deepEquals(lhs.accountType, rhs.accountType) && AccountManagerApiPigeonInternal.deepEquals(lhs.displayName, rhs.displayName) && AccountManagerApiPigeonInternal.deepEquals(lhs.userData, rhs.userData)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AccountData")
    AccountManagerApiPigeonInternal.deepHash(value: username, hasher: &hasher)
    AccountManagerApiPigeonInternal.deepHash(value: accountType, hasher: &hasher)
    AccountManagerApiPigeonInternal.deepHash(value: displayName, hasher: &hasher)
    AccountManagerApiPigeonInternal.deepHash(value: userData, hasher: &hasher)
  }

  public var description: String {
    return "AccountData(username: \(String(describing: username)), accountType: \(String(describing: accountType)), displayName: \(String(describing: displayName)), userData: \(String(describing: userData)))"
  }
}

/// Auth token request result
///
/// Generated class from Pigeon that represents data sent in messages.
struct AuthTokenResult: Hashable, CustomStringConvertible {
  var token: String? = nil
  var errorCode: Int64? = nil
  var errorMessage: String? = nil
  var requiresUserInteraction: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AuthTokenResult? {
    let token: String? = nilOrValue(pigeonVar_list[0])
    let errorCode: Int64? = nilOrValue(pigeonVar_list[1])
    let errorMessage: String? = nilOrValue(pigeonVar_list[2])
    let requiresUserInteraction: Bool? = nilOrValue(pigeonVar_list[3])

    return AuthTokenResult(
      token: token,
      errorCode: errorCode,
      errorMessage: errorMessage,
      requiresUserInteraction: requiresUserInteraction
    )
  }
  func toList() -> [Any?] {
    return [
      token,
      errorCode,
      errorMessage,
      requiresUserInteraction,
    ]
  }
  static func == (lhs: AuthTokenResult, rhs: AuthTokenResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return AccountManagerApiPigeonInternal.deepEquals(lhs.token, rhs.token) && AccountManagerApiPigeonInternal.deepEquals(lhs.errorCode, rhs.errorCode) && AccountManagerApiPigeonInternal.deepEquals(lhs.errorMessage, rhs.errorMessage) && AccountManagerApiPigeonInternal.deepEquals(lhs.requiresUserInteraction, rhs.requiresUserInteraction)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AuthTokenResult")
    AccountManagerApiPigeonInternal.deepHash(value: token, hasher: &hasher)
    AccountManagerApiPigeonInternal.deepHash(value: errorCode, hasher: &hasher)
    AccountManagerApiPigeonInternal.deepHash(value: errorMessage, hasher: &hasher)
    AccountManagerApiPigeonInternal.deepHash(value: requiresUserInteraction, hasher: &hasher)
  }

  public var description: String {
    return "AuthTokenResult(token: \(String(describing: token)), errorCode: \(String(describing: errorCode)), errorMessage: \(String(describing: errorMessage)), requiresUserInteraction: \(String(describing: requiresUserInteraction)))"
  }
}

private class AccountManagerApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return AccountData.fromList(self.readValue() as! [Any?])
    case 130:
      return AuthTokenResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class AccountManagerApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? AccountData {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? AuthTokenResult {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class AccountManagerApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return AccountManagerApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return AccountManagerApiPigeonCodecWriter(data: data)
  }
}

class AccountManagerApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = AccountManagerApiPigeonCodec(readerWriter: AccountManagerApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AccountManagerHostApi {
  func addAccount(account: AccountData, password: String, completion: @escaping (Result<Bool, Error>) -> Void)
  func getAccounts(accountType: String, completion: @escaping (Result<[AccountData], Error>) -> Void)
  func getAccount(username: String, accountType: String, completion: @escaping (Result<AccountData?, Error>) -> Void)
  func updateAccount(account: AccountData, completion: @escaping (Result<Bool, Error>) -> Void)
  func removeAccount(account: AccountData, completion: @escaping (Result<Bool, Error>) -> Void)
  func accountExists(username: String, accountType: String, completion: @escaping (Result<Bool, Error>) -> Void)
  func updateCredentials(account: AccountData, newPassword: String, completion: @escaping (Result<Bool, Error>) -> Void)
  func validateCredentials(username: String, password: String, accountType: String, completion: @escaping (Result<Bool, Error>) -> Void)
  func clearCredentials(account: AccountData, completion: @escaping (Result<Bool, Error>) -> Void)
  func getAuthToken(account: AccountData, tokenType: String, completion: @escaping (Result<AuthTokenResult, Error>) -> Void)
  func setAuthToken(account: AccountData, tokenType: String, token: String, completion: @escaping (Result<Bool, Error>) -> Void)
  func invalidateAuthToken(accountType: String, token: String, completion: @escaping (Result<Bool, Error>) -> Void)
  func invalidateAllTokens(account: AccountData, tokenType: String, completion: @escaping (Result<Bool, Error>) -> Void)
  func getAvailableTokenTypes(account: AccountData, completion: @escaping (Result<[String], Error>) -> Void)
  func openAccountSettings(completion: @escaping (Result<Bool, Error>) -> Void)
  func isConfigured(completion: @escaping (Result<Bool, Error>) -> Void)
  func getPlatformCapabilities(completion: @escaping (Result<[String: Bool], Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AccountManagerHostApiSetup {
  static var codec: FlutterStandardMessageCodec { AccountManagerApiPigeonCodec.shared }
  /// Sets up an instance of `AccountManagerHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AccountManagerHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let addAccountChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_account_manager.AccountManagerHostApi.addAccount\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addAccountChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let accountArg = args[0] as! AccountData
        let passwordArg = args[1] as! String
        api.addAccount(account: accountArg, password: passwordArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      addAccountChannel.setMessageHandler(nil)
    }
    let getAccountsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_account_manager.AccountManagerHostApi.getAccounts\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAccountsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let accountTypeArg = args[0] as! String
        api.getAccounts(accountType: accountTypeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getAccountsChannel.setMessageHandler(nil)
    }
    let getAccountChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_account_manager.AccountManagerHostApi.getAccount\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAccountChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let usernameArg = args[0] as! String
        let accountTypeArg = args[1] as! String
        api.getAccount(username: usernameArg, accountType: accountTypeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getAccountChannel.setMessageHandler(nil)
    }
    let updateAccountChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_account_manager.AccountManagerHostApi.updateAccount\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateAccountChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let accountArg = args[0] as! AccountData
        api.updateAccount(account: accountArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      updateAccountChannel.setMessageHandler(nil)
    }
    let removeAccountChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_account_manager.AccountManagerHostApi.removeAccount\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      removeAccountChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let accountArg = args[0] as! AccountData
        api.removeAccount(account: accountArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      removeAccountChannel.setMessageHandler(nil)
    }
    let accountExistsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_account_manager.AccountManagerHostApi.accountExists\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      accountExistsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let usernameArg = args[0] as! String
        let accountTypeArg = args[1] as! String
        api.accountExists(username: usernameArg, accountType: accountTypeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      accountExistsChannel.setMessageHandler(nil)
    }
    let updateCredentialsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_account_manager.AccountManagerHostApi.updateCredentials\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateCredentialsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let accountArg = args[0] as! AccountData
        let newPasswordArg = args[1] as! String
        api.updateCredentials(account: accountArg, newPassword: newPasswordArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      updateCredentialsChannel.setMessageHandler(nil)
    }
    let validateCredentialsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_account_manager.AccountManagerHostApi.validateCredentials\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      validateCredentialsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let usernameArg = args[0] as! String
        let passwordArg = args[1] as! String
        let accountTypeArg = args[2] as! String
        api.validateCredentials(username: usernameArg, password: passwordArg, accountType: accountTypeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      validateCredentialsChannel.setMessageHandler(nil)
    }
    let clearCredentialsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_account_manager.AccountManagerHostApi.clearCredentials\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearCredentialsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let accountArg = args[0] as! AccountData
        api.clearCredentials(account: accountArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      clearCredentialsChannel.setMessageHandler(nil)
    }
    let getAuthTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_account_manager.AccountManagerHostApi.getAuthToken\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAuthTokenChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let accountArg = args[0] as! AccountData
        let tokenTypeArg = args[1] as! String
        api.getAuthToken(account: accountArg, tokenType: tokenTypeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getAuthTokenChannel.setMessageHandler(nil)
    }
    let setAuthTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_account_manager.AccountManagerHostApi.setAuthToken\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setAuthTokenChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let accountArg = args[0] as! AccountData
        let tokenTypeArg = args[1] as! String
        let tokenArg = args[2] as! String
        api.setAuthToken(account: accountArg, tokenType: tokenTypeArg, token: tokenArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setAuthTokenChannel.setMessageHandler(nil)
    }
    let invalidateAuthTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_account_manager.AccountManagerHostApi.invalidateAuthToken\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      invalidateAuthTokenChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let accountTypeArg = args[0] as! String
        let tokenArg = args[1] as! String
        api.invalidateAuthToken(accountType: accountTypeArg, token: tokenArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      invalidateAuthTokenChannel.setMessageHandler(nil)
    }
    let invalidateAllTokensChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_account_manager.AccountManagerHostApi.invalidateAllTokens\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      invalidateAllTokensChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let accountArg = args[0] as! AccountData
        let tokenTypeArg = args[1] as! String
        api.invalidateAllTokens(account: accountArg, tokenType: tokenTypeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      invalidateAllTokensChannel.setMessageHandler(nil)
    }
    let getAvailableTokenTypesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_account_manager.AccountManagerHostApi.getAvailableTokenTypes\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAvailableTokenTypesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let accountArg = args[0] as! AccountData
        api.getAvailableTokenTypes(account: accountArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getAvailableTokenTypesChannel.setMessageHandler(nil)
    }
    let openAccountSettingsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_account_manager.AccountManagerHostApi.openAccountSettings\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openAccountSettingsChannel.setMessageHandler { _, reply in
        api.openAccountSettings { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      openAccountSettingsChannel.setMessageHandler(nil)
    }
    let isConfiguredChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_account_manager.AccountManagerHostApi.isConfigured\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isConfiguredChannel.setMessageHandler { _, reply in
        api.isConfigured { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      isConfiguredChannel.setMessageHandler(nil)
    }
    let getPlatformCapabilitiesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_account_manager.AccountManagerHostApi.getPlatformCapabilities\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getPlatformCapabilitiesChannel.setMessageHandler { _, reply in
        api.getPlatformCapabilities { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getPlatformCapabilitiesChannel.setMessageHandler(nil)
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol AccountCallbackFlutterApiProtocol {
  @MainActor func onAccountAdded(account accountArg: AccountData) async throws
  @MainActor func onAccountRemoved(account accountArg: AccountData) async throws
  @MainActor func onAccountUpdated(account accountArg: AccountData) async throws
  @MainActor func onAuthTokenExpired(account accountArg: AccountData, tokenType tokenTypeArg: String) async throws
}
class AccountCallbackFlutterApi: AccountCallbackFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: AccountManagerApiPigeonCodec {
    return AccountManagerApiPigeonCodec.shared
  }
  @MainActor func onAccountAdded(account accountArg: AccountData) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.flutter_account_manager.AccountCallbackFlutterApi.onAccountAdded\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([accountArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  @MainActor func onAccountRemoved(account accountArg: AccountData) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.flutter_account_manager.AccountCallbackFlutterApi.onAccountRemoved\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([accountArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  @MainActor func onAccountUpdated(account accountArg: AccountData) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.flutter_account_manager.AccountCallbackFlutterApi.onAccountUpdated\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([accountArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  @MainActor func onAuthTokenExpired(account accountArg: AccountData, tokenType tokenTypeArg: String) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.flutter_account_manager.AccountCallbackFlutterApi.onAuthTokenExpired\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([accountArg, tokenTypeArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
}
